/* Shared alert workspace. Original event types and unknown identities stay intact. */
window.AlertsWorkspace={mount(root,{base,fetcher=window.fetch.bind(window)}){
 if(root._alerts)return root._alerts;
 root.className='attendance-workspace';const node=(tag,value)=>{const n=document.createElement(tag);if(value!==undefined)n.textContent=value;return n;};
 root.replaceChildren(node('h2','Alerts'));const summary=node('div');summary.className='aw-metrics';root.append(summary);
 const form=node('form');form.className='aw-filters';const fields={};
 function field(key,label,options,type='text'){const wrap=node('label',label),input=node(options?'select':'input');input.name=key;input.setAttribute('aria-label',label);if(options)options.forEach(([value,title])=>{const option=node('option',title);option.value=value;input.append(option);});else input.type=type;fields[key]=input;wrap.append(input);form.append(wrap);}
 field('search','Employee name, code or reason');field('camera_id','Camera ID');field('shop_id','Shop ID');field('type','Original alert type');
 field('status','Alert status',[['','All statuses'],['OPEN','Open'],['ACKNOWLEDGED','Acknowledged'],['RESOLVED','Resolved']]);
 field('severity','Severity',[['','All severities'],['INFO','Info'],['WARNING','Warning'],['CRITICAL','Critical']]);
 field('preset','Date range',[['today','Today'],['yesterday','Yesterday'],['last7','Last 7 days'],['month','This month'],['custom','Custom dates']]);
 field('start','Start date',null,'date');field('end','End date',null,'date');field('timezone','Timezone');fields.timezone.value='Asia/Kolkata';
 field('start_at','Exact start (ISO timestamp with offset)');field('end_at','Exact end (exclusive, with offset)');
 field('sort','Sort by',[['time','Time'],['severity','Severity'],['status','Status']]);field('direction','Order',[['desc','Newest / highest first'],['asc','Oldest / lowest first']]);
 const apply=node('button','Apply filters');apply.type='submit';form.append(apply);root.append(form);
 const message=node('p');message.setAttribute('role','status');root.append(message);
 const exportButton=node('button','Export filtered CSV');root.append(exportButton);const count=node('p');root.append(count);
 const scroll=node('div');scroll.className='aw-scroll';const table=node('table');table.className='aw-table';table.setAttribute('aria-label','Alerts');
 const head=node('thead'),tr=node('tr');['Time','Employee','Type / Severity','Status','Camera / Shop','Reason / Source','Details'].forEach(x=>tr.append(node('th',x)));head.append(tr);table.append(head);const body=node('tbody');table.append(body);scroll.append(table);root.append(scroll);
 const pager=node('div');pager.className='aw-pages';const previous=node('button','Previous'),next=node('button','Next');pager.append(previous,next);root.append(pager);const detail=node('section');root.append(detail);
 let page=1,generation=0;const urls=new Set();function clearMedia(){urls.forEach(u=>URL.revokeObjectURL(u));urls.clear();}
 function params(){const p=new URLSearchParams({page,page_size:25});Object.entries(fields).forEach(([key,input])=>{if(input.value)p.set(key,input.value);});return p;}
 async function json(url,options){const response=await fetcher(url,options);const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:'Request rejected; verify policy/filter values');return data;}
 async function media(url,kind){try{const response=await fetcher(url);if(!response.ok)throw Error('Evidence unavailable');const object=URL.createObjectURL(await response.blob());urls.add(object);const element=node(kind);element.className='aw-preview';if(kind==='video')element.controls=true;element.src=object;detail.append(element);}catch(error){message.textContent=error.message;}}
 async function open(row){try{clearMedia();const value=await json(base+'/'+encodeURIComponent(row.id));detail.replaceChildren(node('h3',value.type.replaceAll('_',' ')),node('p',value.timestamp),node('p',value.employee_name||'No identified employee'),node('p',value.reason),node('p','Source: '+value.source+' · Camera: '+(value.camera_id||'Unknown')+' · Shop: '+value.shop_id),node('p','Status: '+value.status+' · Severity: '+value.severity+' ('+value.severity_basis+')'));
 (value.images||[]).forEach((url,index)=>{const button=node('button','Image '+(index+1));button.onclick=()=>media(url,'img');detail.append(button);});if(value.video){const button=node('button','Video clip');button.onclick=()=>media(value.video,'video');detail.append(button);}if(!value.images?.length&&!value.video)detail.append(node('p','Evidence unavailable'));
 detail.append(node('p','Notification delivery: '+JSON.stringify(value.notifications)),node('h4','Acknowledgment and resolution history'));
 (value.history||[]).forEach(event=>detail.append(node('p',event.occurred_at+' · '+event.previous_status+' → '+event.new_status+' · '+event.actor+' · '+event.reason)));if(!value.history?.length)detail.append(node('p','No operator actions recorded.'));
 if(value.can_edit&&value.status!=='RESOLVED'){const label=node('label','Action reason'),reason=node('input');reason.setAttribute('aria-label','Action reason');label.append(reason);detail.append(label);for(const action of value.status==='OPEN'?['ACKNOWLEDGE','RESOLVE']:['RESOLVE']){const button=node('button',action==='ACKNOWLEDGE'?'Acknowledge':'Resolve');button.onclick=async()=>{if(!reason.value.trim()){message.textContent='A reason is required.';return;}button.disabled=true;try{await json(base+'/'+encodeURIComponent(row.id)+'/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,expected_status:value.status,request_id:crypto.randomUUID(),reason:reason.value})});await load();await open(row);}catch(error){message.textContent=error.message;button.disabled=false;}};detail.append(button);}}
 }catch(error){message.textContent=error.message;}}
 async function load(){const own=++generation;message.textContent='Loading alerts…';try{const data=await json(base+'/workspace?'+params());if(own!==generation)return;summary.replaceChildren();Object.entries(data.summary).forEach(([state,total])=>{const card=node('div');card.className='aw-metric';card.append(node('span',state.replaceAll('_',' ')),node('strong',total));summary.append(card);});body.replaceChildren();for(const row of data.items){const tr=node('tr');[row.timestamp,row.employee_name||'No identified employee',row.type.replaceAll('_',' ')+' / '+row.severity,row.status,row.camera_id+' / '+row.shop_id,row.reason+' / '+row.source].forEach(value=>tr.append(node('td',value)));const td=node('td'),button=node('button','View details');button.onclick=()=>open(row);td.append(button);tr.append(td);body.append(tr);}if(!data.items.length){const tr=node('tr'),td=node('td','No alerts match these filters.');td.colSpan=7;tr.append(td);body.append(tr);}count.textContent=data.total+' matching alerts';previous.disabled=page<=1;next.disabled=page*25>=data.total;message.textContent='Original events remain unchanged; operator actions are recorded separately.';}catch(error){message.textContent=error.message;}}
 form.onsubmit=e=>{e.preventDefault();page=1;load();};previous.onclick=()=>{page--;load();};next.onclick=()=>{page++;load();};
 exportButton.onclick=async()=>{try{const response=await fetcher(base+'/export?'+params());if(!response.ok)throw Error('Export denied');const object=URL.createObjectURL(await response.blob()),a=node('a');a.href=object;a.download='alerts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(object),1000);}catch(error){message.textContent=error.message;}};
 root._alerts={load};load();return root._alerts;
}};
