# Camera Automation Windows Build Script
# This script builds the production package using PyInstaller

param (
    [string]$BuildType = "onedir",  # "onedir" or "onefile"
    [string]$OutputDir = "dist",
    [bool]$CleanBuild = $true,
    [bool]$IncludeDebugSymbols = $false
)

# Configuration
$ProjectName = "CameraAutomation"
$MainScript = "camera_service/launcher.py"
$IconPath = "camera_service/web/favicon.ico"  # Create this if needed
$SpecFile = "packaging/windows/CameraAutomation.spec"
$PythonPath = "python"
$PyInstallerPath = "pyinstaller"

# Ensure we're in the project root
$ProjectRoot = $PSScriptRoot + "\..\.."
Set-Location $ProjectRoot

# Clean previous build if requested
if ($CleanBuild) {
    Write-Host "Cleaning previous build..."
    if (Test-Path "$OutputDir") {
        Remove-Item "$OutputDir" -Recurse -Force
    }
    if (Test-Path "build") {
        Remove-Item "build" -Recurse -Force
    }
}

# Create output directory
if (-not (Test-Path "$OutputDir")) {
    New-Item -ItemType Directory -Path "$OutputDir" | Out-Null
}

# Check if PyInstaller is available
try {
    & $PythonPath -m pip show pyinstaller | Out-Null
} catch {
    Write-Host "PyInstaller not found. Installing..."
    & $PythonPath -m pip install pyinstaller
}

# Create or update the spec file
$SpecContent = @"
# CameraAutomation PyInstaller Spec File
# Generated by build_windows.ps1

block_cipher = None

a = Analysis(
    ['$MainScript'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('camera_service/web/setup.html', 'camera_service/web'),
        ('camera_service/web/*.*', 'camera_service/web'),
        ('data/*.*', 'data'),
        ('models/*.*', 'models'),
        ('*.db', '.'),
    ],
    hiddenimports=[
        'ultralytics',
        'insightface',
        'onnxruntime',
        'cv2',
        'numpy',
        'pydantic',
        'fastapi',
        'uvicorn',
        'yaml',
        'sqlite3',
        'threading',
        'datetime',
        'json',
        're',
        'enum',
        'typing',
        'pathlib',
        'webbrowser',
        'subprocess',
        'socket',
        'sys',
        'os',
        'time',
        'threading',
        'multiprocessing',
        'queue',
        'collections',
        'itertools',
        'functools',
        'operator',
        'math',
        'random',
        'hashlib',
        'base64',
        'zlib',
        'gzip',
        'bz2',
        'lzma',
        'pickle',
        'shelve',
        'configparser',
        'argparse',
        'getopt',
        'logging',
        'warnings',
        'contextlib',
        'abc',
        'io',
        'tempfile',
        'shutil',
        'glob',
        'fnmatch',
        'urllib',
        'http',
        'ftplib',
        'smtplib',
        'poplib',
        'imaplib',
        'nntplib',
        'socketserver',
        'http.server',
        'http.cookiejar',
        'http.cookies',
        'email',
        'mimetypes',
        'json',
        'csv',
        'xml',
        'html',
        'urllib.parse',
        'urllib.request',
        'urllib.error',
        'urllib.robotparser',
        'http.client',
        'ftplib',
        'smtplib',
        'poplib',
        'imaplib',
        'nntplib',
        'socketserver',
        'http.server',
        'http.cookiejar',
        'http.cookies',
        'email',
        'mimetypes',
        'json',
        'csv',
        'xml',
        'html',
        'urllib.parse',
        'urllib.request',
        'urllib.error',
        'urllib.robotparser',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False
)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='$ProjectName',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    icon='$IconPath'
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='$ProjectName'
)
"@

# Write the spec file
$SpecContent | Out-File -FilePath $SpecFile -Encoding utf8

# Build the application
Write-Host "Building Camera Automation ($BuildType mode)..."

$BuildArgs = @(
    "--$BuildType",
    "--name", "$ProjectName",
    "--distpath", "$OutputDir",
    "--workpath", "build",
    "--specpath", "packaging/windows",
    "--clean"
)

if ($IncludeDebugSymbols) {
    $BuildArgs += "--debug=all"
}

if (Test-Path $IconPath) {
    $BuildArgs += "--icon", "$IconPath"
}

try {
    Write-Host "Running PyInstaller..."
    & $PyInstallerPath @BuildArgs $SpecFile

    Write-Host "Build completed successfully!"
    Write-Host "Output directory: $OutputDir"

    # Check if the build was successful
    $ExpectedPath = Join-Path $OutputDir $ProjectName
    if ($BuildType -eq "onedir") {
        $ExpectedPath = Join-Path $ExpectedPath "$ProjectName.exe"
    } else {
        $ExpectedPath = Join-Path $ExpectedPath ".exe"
    }

    if (Test-Path $ExpectedPath) {
        Write-Host "Build successful! Executable created at: $ExpectedPath"
    } else {
        Write-Host "Build may have failed. Expected executable not found at: $ExpectedPath"
    }
} catch {
    Write-Host "Build failed with error: $_"
    exit 1
}

# Create start/stop scripts
$StartScriptContent = @"
@echo off
SETLOCAL

REM Camera Automation Start Script
REM This script starts the Camera Automation application

SET APP_DIR=%~dp0
SET APP_NAME=CameraAutomation.exe

echo Starting Camera Automation...
echo Application Directory: %APP_DIR%

cd /d "%APP_DIR%"

if exist "%APP_NAME%" (
    start "" "%APP_NAME%"
    echo Camera Automation started successfully.
    echo Opening browser to setup page...
    timeout /t 2 /nobreak >nul
    start "" "http://127.0.0.1:8000/setup"
) else (
    echo Error: %APP_NAME% not found in %APP_DIR%
    pause
)

ENDLOCAL
"@

$StopScriptContent = @"
@echo off
SETLOCAL

REM Camera Automation Stop Script
REM This script stops the Camera Automation application

echo Stopping Camera Automation...

taskkill /f /im CameraAutomation.exe >nul 2>&1
taskkill /f /im python.exe >nul 2>&1

echo Camera Automation stopped.
pause

ENDLOCAL
"@

# Write start/stop scripts
$StartScriptContent | Out-File -FilePath "START_CAMERA_AUTOMATION.bat" -Encoding utf8
$StopScriptContent | Out-File -FilePath "STOP_CAMERA_AUTOMATION.bat" -Encoding utf8

Write-Host "Created START_CAMERA_AUTOMATION.bat and STOP_CAMERA_AUTOMATION.bat"

# Create .env.example file
$EnvExampleContent = @"
# Camera Automation Configuration
# Copy this file to .env and modify as needed

# Server Configuration
HOST=127.0.0.1
PORT=8000

# Data Directory (Windows)
DATA_DIR=C:\ProgramData\CameraAutomation

# Logging
LOG_LEVEL=INFO

# Feature Flags
FACE_RECOGNITION_ENABLED=true
ATTENDANCE_ENABLED=true
UNKNOWN_DETECTION_ENABLED=true

# Face Recognition Settings
FACE_KNOWN_THRESHOLD=0.65
FACE_REQUIRED_OBSERVATIONS=3

# Unknown Person Settings
UNKNOWN_CONFIRM_SECONDS=3

# Auto-open browser on startup
AUTO_OPEN_BROWSER=true

# Debug mode
DEBUG=false
"@

$EnvExampleContent | Out-File -FilePath ".env.example" -Encoding utf8
Write-Host "Created .env.example file"

Write-Host "Build process completed!"